name: Deploy CRM

on:
  push:
    branches: ["demo"]                

jobs:
  build-and-deploy:
    runs-on: crm
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # - name: 'Restart'
    #   shell: pwsh # For Linux, use bash
    #   run: |
    #     pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    #     npm install
    #     npm run build --if-present
    #     npm run test --if-present
    #     popd
